# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Parser/Test

# Rules for building the parser.

Parser/ErrM.hs Parser/Lex.x Parser/Print.hs Parser/Par.y Parser/Test.hs : src/Parser/Parser.cf
	bnfc --haskell -d src/Parser/Parser.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

Parser/Test : Parser/Test.hs Parser/ErrM.hs Parser/Lex.hs Parser/Par.hs Parser/Print.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f Parser/*.hi Parser/*.o Parser/*.log Parser/*.aux Parser/*.dvi

distclean : clean
	-rm -f Parser/Abs.hs Parser/Abs.hs.bak Parser/ComposOp.hs Parser/ComposOp.hs.bak Parser/Doc.txt Parser/Doc.txt.bak Parser/ErrM.hs Parser/ErrM.hs.bak Parser/Layout.hs Parser/Layout.hs.bak Parser/Lex.x Parser/Lex.x.bak Parser/Par.y Parser/Par.y.bak Parser/Print.hs Parser/Print.hs.bak Parser/SharedString.hs Parser/SharedString.hs.bak Parser/Skel.hs Parser/Skel.hs.bak Parser/Test.hs Parser/Test.hs.bak Parser/XML.hs Parser/XML.hs.bak Parser/AST.agda Parser/AST.agda.bak Parser/Parser.agda Parser/Parser.agda.bak Parser/IOLib.agda Parser/IOLib.agda.bak Parser/Main.agda Parser/Main.agda.bak Parser/Parser.dtd Parser/Parser.dtd.bak Parser/Test Parser/Lex.hs Parser/Par.hs Parser/Par.info Parser/ParData.hs Makefile
	-rmdir -p Parser/

# EOF
