name:                qfunc
version:             0.1.0.0
github:              "NicklasBoto/funQ"
license:             GPL-3
author:
  - Nicklas Botö
  - Fabian Forslund
  - Matilda Blomqvist
  - Beata Burreau
  - Marcus Jörgensson
  - Joel Rudsberg
maintainer:          "qfunc@nicbot.xyz"
copyright:           "2021 Nicklas Botö"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/NicklasBoto/qfunc#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- bitvec
- MonadRandom
- mtl
- numbers
- array
- containers
- haskeline
- repline == 0.4.0.0
- turtle
- parsec

library:
  when:
    - condition: false
      other-modules: Paths_pkg
  source-dirs: 
    - src
    - examples

executables:
  funq:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qfunc

tests:
  qfunc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qfunc
    - QuickCheck
