name:                qfunc
version:             0.1.0.0
github:              "NicklasBoto/qfunc"
license:             GPL-3
author:
  - Nicklas Botö
  - Fabian Forslund
  - Matilda Blomqvist
  - Beata Burreau
  - Marcus Jörgensson
  - Joel Rudsberg
maintainer:          "qfunc@nicbot.xyz"
copyright:           "2020 Nicklas Botö"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/qfunc#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- bitvec
- type-natural
- ghc-typelits-knownnat
- MonadRandom

library:
  source-dirs: src

executables:
  qfunc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qfunc

tests:
  qfunc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qfunc
    - QuickCheck
