name: github-pages

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Generate docs and deploy to github pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate docs
        run: stack haddock

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

